baseURL = 'https://luabyexample.org/'
languageCode = 'en-us'
title = "Lua by Example"

[markup]
  [markup.highlight]
    anchorLineNos = false
    guessSyntax = false
    lineNos = false
    style = 'perldoc'
    tabWidth = 4

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

enableGitInfo = true

[params]
BookTheme = 'light'
BookRepo = 'https://github.com/barklan/luabyexample'
BookEditPath = 'edit/main'
BookLogo = 'logo.png'
BookToC = false
