baseURL: https://luabyexample.netlify.app/
languageCode: en-us
title: Lua by Example
enableGitInfo: true
menu:
  main:
    - name: Lua by Example
      url: /
      weight: 1
    - name: Source
      url: 'https://github.com/barklan/luabyexample'
      weight: 2

markup:
  highlight:
    codeFences: true
    style: bw
    lineNumbersInTable: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html

module:
  imports:
    - path: github.com/barklan/hugo-dead-simple
