baseURL: https://luabyexample.netlify.app/
languageCode: en-us
title: Lua by Example
menu:
  main:
    - name: Lua by Example
      url: /
      weight: 1
    - name: Source
      url: 'https://github.com/barklan/luabyexample'
      weight: 2

markup:
  highlight:
    codeFences: true
    style: bw
    lineNumbersInTable: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
    - path: github.com/barklan/hugo-dead-simple
